### ISSUE TITLE
t-shirt_male not found

### ISSUE THREAD

**Issue by yuxwind** [zycliao/TailorNet_dataset#1]
Thanks for releasing the dataset! 

Just a reminder that there is a small typo in the link for t-shirt_male. It should be 
```https://datasets.d2.mpi-inf.mpg.de/tailornet/t-shirt_male.zip```
instead of
```https://datasets.d2.mpi-inf.mpg.de/tailornet/t-shirt_male.zxip```

**Comment by zycliao** [comment]
Thanks for pointing out. It's fixed.
