### ISSUE TITLE
Using beta causes error in matrix manipulation while visualizing dataset

### ISSUE THREAD

**Issue by Lotemn102** [zycliao/TailorNet_dataset#10]
#### Issue description
I'm trying to visualize the `t-shirt_female` sub-dataset. 
When i run the script in `visualize_dataset.py`, i'm getting the following error:
```
Traceback (most recent call last):
  File "/home/lotemn/Desktop/vtom/TailorNet_dataset-master/visualize_dataset.py", line 53, in <module>
    all_body, all_gar = smpl(np.tile(beta[None], [n, 1]), thetas, unpose_v, garment_class, batch=True)
  File "/home/lotemn/Desktop/vtom/TailorNet_dataset-master/smpl_torch.py", line 474, in __call__
    vbody, vcloth = self.base.forward(theta=theta[lp: rp], beta=beta[lp: rp], garment_d=garment_d[lp: rp], garment_class=garment_class)
  File "/home/lotemn/Desktop/vtom/TailorNet_dataset-master/smpl_torch.py", line 187, in forward
    v_shaped = torch.matmul(beta, self.shapedirs).view(-1, self.size[0], self.size[1]) + self.v_template
RuntimeError: mat1 and mat2 shapes cannot be multiplied (100x300 and 10x82662)
```

#### Steps to reproduce the issue

1.  Follow the instructions on `SMPL model` section in this repo's README.md. 
2. Download dataset_meta.zip [here](https://nextcloud.mpi-klsb.mpg.de/index.php/s/W7a57iXRG9Yms6P).
3. Download the `t-shirt_female(6.9G)` sub-dataset [here](https://nextcloud.mpi-klsb.mpg.de/index.php/s/W7a57iXRG9Yms6P).
3. Specify the variable ROOT in `global_var.py`.
4. Unzip all downloaded files to ROOT.
5. Run `visualize_dataset.py`.

#### What's the expected result?
- Output of the animated dataset objects as MP4 videos.

#### What's the actual result?

- The error i've added before.

#### Environment
- Ubuntu 20.04.
- Python 3.8.
- I'm running on a CPU.

#### Additional details
The problem is caused by the following lines:
https://github.com/zycliao/TailorNet_dataset/blob/45881bc30e24031d2b4f324322efd5fd5701b0b4/smpl_torch.py#L184-L185

By simply removing these lines, and forcing the script to go to the `else` part of this condition, the error is solved and the desired output is being generated.

Not sure about that `beta` tensor. What's it's purpose?

**Comment by chaitanya100100** [comment]
Hello Lotem,
I greatly appreciate the efforts you have put describing the details of the bug. And sorry for that bug, it's a silly mistake from our part.
`beta` parameters denote the shape of the body - shape broadly defines the height and width of the body.
Now for the error, it is due to the mismatch of the parameters length. You can replace `beta` with `beta[:, :10]` as described below and it would work.
```
if beta is not None: 
     v_shaped = torch.matmul(beta[:, :10], self.shapedirs).view(-1, self.size[0], self.size[1]) + self.v_template
```
Adding @zycliao to the thread to correct that line in the code.

**Comment by Lotemn102** [comment]
The error resolved with the change you suggested. Thank you very much!
