### ISSUE TITLE
About simulation .pc2

### ISSUE THREAD

**Issue by lanchen2019** [zycliao/TailorNet_dataset#11]
Thanks for sharing this wonderful work and meaningful data! I have a problem about data generation. How to get .pc2 file with multiple obj sequences? Is any method  to use the python scripts in marvelous designer? Thanks if you can help.

**Comment by zycliao** [comment]
What do you mean by "multiple obj sequences"?  You can refer to https://github.com/zycliao/TailorNet_dataset/blob/master/simulation_pose/gen_motion.py

We didn't manage to use scripts in Marvelous Designer. Instead, we use pyautogui to automatically interact with the UI. If you want to do simulation yourself, I'd suggest trying with simulators supporting scripts, e.g. Blender.
