### ISSUE TITLE
FileNotFoundError on gamma_000.npy

### ISSUE THREAD

**Issue by zahrahosseini99** [zycliao/TailorNet_dataset#12]
Hi,
I get this error while I'm trying to run the TailorNet,
`FileNotFoundError: [Errno 2] No such file or directory: '/content/TailorNet_dataset/skirt_female/style/gamma_000.npy'`
The file's name has changed? Or how can I find this file?

**Comment by zycliao** [comment]
Please download and unzip the latest inference_data.zip in https://nextcloud.mpi-klsb.mpg.de/index.php/s/W7a57iXRG9Yms6P

**Comment by zahrahosseini99** [comment]
Oh no, It is not my question right now!
I have the same problem as this issue
<https://github.com/zycliao/TailorNet_dataset/issues/7#issue-811754126>,
and your solution didn't work. I'm trying to run the code on Google Colab.
Would you please take a look at it? I really appreciate any help you can
provide.
https://github.com/zycliao/TailorNet_dataset/issues/7#issuecomment-918913669 it
is my question:(

[image: image.png]
