### ISSUE TITLE
Garment displacement calculation in dataset

### ISSUE THREAD

**Issue by hguomin** [zycliao/TailorNet_dataset#16]
Hi Yingcheng,

Thanks for sharing this great work. 

I read through the code to generate this dataset for training the TailorNet, found that the displacement between the garment and human body is originally loaded from the raw data in this [file](https://github.com/zycliao/TailorNet_dataset/blob/master/style_pca/copy_raw.py), would you be able to share the method that you calculate this displacement values? 

Other question is that I found the "garment_class_info.pkl" place a key role in the code, it defines the garment templates based on the SMPL mesh, so would like to know how do you generate the data in this file? I mean the approach marking the vertices in SMPL, generating the garment mesh vertices, etc. 

Many thanks!

**Comment by zycliao** [comment]
Hi,

The displacement data is from MGN (https://github.com/bharat-b7/MultiGarmentNetwork). The public data format is different from what I used, so you might need to write your own code.

The garment template is manually defined. It is a submesh of upsampled SMPL body.
