### ISSUE TITLE
Create new garment of dataset

### ISSUE THREAD

**Issue by phnb** [zycliao/TailorNet_dataset#17]
Hi author,
I want to follow your instructions and create a new garment class myself to test the model. But I have encountered several problems as follows:
1. how can you decide the the vertices number and position of one kind of garment, since garment are considered as one part of SMPL body and garment_class_info.pkl['vert_indices'] states the vertices postions, e.g. 'pant': 4718
2. What is the input of copy_raw.py /BS/bharat-2/work/data/renderings? Can you provide some clues of how renderings files organized?
3. Here I want to use the registration file of MGN dataset of following long cloth mesh, can you provide some instructions on how to handle this mesh file.
![snapshot00](https://user-images.githubusercontent.com/73104786/162875330-5a90f24f-c454-4356-914e-4e7f3fff3325.png)
Thanks!!!

**Comment by zycliao** [comment]
Hi,

1. It was manually defined by selecting a subset of SMPL mesh
2. They are garments from MGN (https://github.com/bharat-b7/MultiGarmentNetwork) dataset, but the data format is different from the public one. "beta" is available in the dataset. What you have to do is calculating "garment offsets" (which is the displacement of the garment from the body in zero pose). 
3. It should be a similar procedure as in 2.

**Comment by phnb** [comment]
Sorry, but for question one, what do you mean "manually"?
Many thanks!!!

**Comment by zycliao** [comment]
It means we used a 3D software to select a submesh from the SMPL mesh
