### ISSUE TITLE
Segmentation Fault

### ISSUE THREAD

**Issue by rylzxc** [zycliao/TailorNet_dataset#19]
While trying to visualise the dataset, I encounter segmentation fault. How to resolve?

<img width="1792" alt="Screenshot 2022-07-14 at 01 41 59" src="https://user-images.githubusercontent.com/97279671/178797506-b77788ba-9e0c-4b27-ab7a-727072abd93f.png">

**Comment by rylzxc** [comment]
I have:
1. python 3.9.12
2. PyTorch 1.12.0
3. chumpy 0.70
4. opencv-python 4.6.0.66
5. python 0.29.30

**Comment by rylzxc** [comment]
After adding `import faulthandler; faulthandler.enable()` , the following errors were thrown, any idea on how to resolve?
<img width="894" alt="Screenshot 2022-07-15 at 02 42 04" src="https://user-images.githubusercontent.com/97279671/179058995-cf0c0c32-5a65-4ce7-af5a-8c96d2f416fc.png">

**Comment by zycliao** [comment]
Hi, can you locate which line of code leads to the segmentation fault?

**Comment by rylzxc** [comment]
Hi, thanks for replying, I'm not sure because that's all I get from the terminal. 

But I also saw 2 errors yesterday, which _may_ have led to the segmentation fault?

1. OpenCV: FFMPEG: tag 0x44495658/'XVID' is not supported with codec id 12 and format 'mp4 / MP4 (MPEG-4 Part 14)'
OpenCV: FFMPEG: fallback to use tag 0x7634706d/'mp4v' (visualise_dataset.py line 57)

2. UserWarning: This overload of sub is deprecated (smpl_torch.py line 277)

**Comment by zycliao** [comment]
We wrote the visualization scripts to help people understand how the dataset is organized and how to convert the dataset into common formats (mesh). You can easily export meshes by modifying the visualization code a little bit.

Each mesh file only contains a garment with a specific beta/gamma. So you cannot modify beta/gamma after importing a mesh to Blender.
