### ISSUE TITLE
Where does the geometry of old-t-shirt come from?

### ISSUE THREAD

**Issue by raxxerwan** [zycliao/TailorNet_dataset#2]
Hi! Thank you for your excellent work!

You've mentioned that you generate your dataset from MGN's dataset Digital Wardrobe. I notice that in Digital Wardrobe, a t-shirt mesh consists of 7702 vertices, which is the same with your t-shirt mesh. But I didn't find any t-shirt with 8168 vertices (which an old-t-shirt mesh consists of) in Digital Wardrobe. So I wonder where do you generate your dataset for old-t-shirt?

Thanks in advance!

**Comment by zycliao** [comment]
We used an older version of MGN dataset to generate old t-shirt. You could write to MGN's authors if you want to know more about it.

**Comment by raxxerwan** [comment]
Got it. Thanks!
