### ISSUE TITLE
Issue with calc_skirt_weight.py

### ISSUE THREAD

**Issue by rylzxc** [zycliao/TailorNet_dataset#20]
Hi, in this file on [lines 25 and 26](https://github.com/zycliao/TailorNet_dataset/blob/66f26cb0577f322a207846ce6cce68faee46b888/calc_skirt_weight.py#L25), where do I get the `skirt_upper_boundary.npy` or `pant_upper_boundary.npy` files?

Else, I won't be able to run the code to generate the `skirt_weight.npz` file [for use in TailorNet](https://github.com/chaitanya100100/TailorNet/blob/09e2830d3f609c4056bc602cb7f87d820282f95e/models/smpl4garment.py#L25)

Thanks!

**Comment by zycliao** [comment]
`*boundary.npy` files contain the indexes of upper boundary vertices of skirt/pants. They are manually obtained.

**Comment by zycliao** [comment]
If you just want to use the `skirt_weight.npz` that is used in TailorNet paper or you want to check its format, it is contained in [dataset_meta.zip](https://nextcloud.mpi-klsb.mpg.de/index.php/s/W7a57iXRG9Yms6P).

**Comment by rylzxc** [comment]
Thanks!
