### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: './smpl/part_shirt.obj'

### ISSUE THREAD

**Issue by g-gaurav** [zycliao/TailorNet_dataset#4]
from where I can get this file

**Comment by zycliao** [comment]
Hi, it's now available [here](https://nextcloud.mpi-klsb.mpg.de/index.php/s/dQCHykYo77EQYS8). Download datagen_assets.zip and unzip it in the root of data directory. Please let me know if there's any other file missing.

**Comment by g-gaurav** [comment]
Thanks a lot for the quick reply.
