### ISSUE TITLE
/simulation_pose/gen_pose_utils.py", line 72, in __init__    with open(os.path.join(pose_dir, 'male.pkl')) as f: FileNotFoundError: [Errno 2] No such file or directory: 'Data/pose/SMPL/male.pkl'

### ISSUE THREAD

**Issue by g-gaurav** [zycliao/TailorNet_dataset#5]
While trying to generate poses. needs some file.

**Comment by zycliao** [comment]
Please download and unzip this. You'll need files under the folder 'pose'
https://nextcloud.mpi-klsb.mpg.de/index.php/s/kHeMxdRyXSLEAYr
