### ISSUE TITLE
Getting error while converting smpl models - ModuleNotFoundError: No module named 'smpl_lib'

### ISSUE THREAD

**Issue by aapatre** [zycliao/TailorNet_dataset#7]
![image](https://user-images.githubusercontent.com/20199688/108468398-b3b72e00-72ac-11eb-9c91-dfadbb56dedf.png)

I'm getting the following error after running `python smpl_lib/convert_smpl_models.py`

```
Traceback (most recent call last):
  File "convert_smpl_models.py", line 7, in <module>
    from smpl_lib.smpl_paths import SmplPaths
ModuleNotFoundError: No module named 'smpl_lib'
```
All the above paths are valid and have been double checked using `os.path.isdir(path)` and `os.path.isfile(path)`

Thanks :)

**Comment by zycliao** [comment]
Do you add the project root directory (/.../TailorNet_dataset) to `PYTHONPATH`?
For example, `export PYTHONPATH=/.../TailorNet_dataset:$PYTHONPATH`

**Comment by aapatre** [comment]
Thanks a lot for your quick response! It fixed the issue! :fire:

**Comment by zahrahosseini99** [comment]
Hi, I have the same problem, and your solution didn't work. I'm trying to run the code on Google Colab. Would you please take a look at it? I really appreciate any help you can provide. @zycliao @chaitanya100100 
![image](https://user-images.githubusercontent.com/48201383/133219795-a381efe0-3aef-4506-9612-8f11bb58bbae.png)

**Comment by zycliao** [comment]
> Hi, I have the same problem, and your solution didn't work. I'm trying to run the code on Google Colab. Would you please take a look at it? I really appreciate any help you can provide. @zycliao @chaitanya100100
> ![image](https://user-images.githubusercontent.com/48201383/133219795-a381efe0-3aef-4506-9612-8f11bb58bbae.png)

Hey. Can you  try adding the following code before importing?
```
  import sys
  sys.path.append("/content/TailorNet_dataset")
