### ISSUE TITLE
RuntimeError: mat1 and mat2 shapes cannot be multiplied (100x300 and 10x82662)

### ISSUE THREAD

**Issue by aapatre** [zycliao/TailorNet_dataset#8]
I'm getting the above runtime error after running `python visualize_dataset.py`

Got the same error after changing the variables to the gender 'male' & style to  'short-pants'.

Any ideas on fixing this?

**Comment by zycliao** [comment]
Try using only the first 10 components of beta. After Line 42, 77 of `visualize_dataset.py`, add `beta = beta[:10]`.

**Comment by aapatre** [comment]
Thanks a lot! The visualizations are successful!
Congrats on your amazing work! :smile:
