### ISSUE TITLE
How can we pass a customized apparel & character mesh as inputs to tailornet for inference?

### ISSUE THREAD

**Issue by Vikas-Sony** [zycliao/TailorNet_dataset#9]
Is it possible to pass a custom male t-shirt OBJ mesh & a male character to infer it via the male_t-shirt class?

**Comment by zycliao** [comment]
Hi, sorry for the late reply. TailorNet uses per-vertex displacement to represent the garment deformation. So your mesh must have the same topology (triangulation) as TailorNet.  If you have such meshes (for example you register your garment mesh to TailorNet mesh), a possible solution is to find the closest gamma and use TailorNet then.

**Comment by Vikas-Sony** [comment]
Hi,
Thanks for replying. We actually have the obj files for garment and body and want to run inference on them using run_tailornet.py. For that, we want to convert these object files into numpy arrays as these numpy arrays are the input used in run_tailornet. So, basically we are having a hard time converting obj files into numpy arrays. Is there any way to do this?

**Comment by zycliao** [comment]
The numpy arrays used in `run_tailornet.py` are not garment or body meshes but SMPL parameters and garment style parameters. To obtain those parameters from arbitrary body/garment meshes, you need to do non-rigid mesh registration.

**Comment by Vikas-Sony** [comment]
Please excuse my ignorance as i am new to 3D human modelling. But can you please tell me how to go about doing non-rigid mesh registration?  Some links which might help me understand. Basically how can i get SMPL parameters and garment style parameters from meshes as you mentioned? Thanks in advance.

**Comment by zycliao** [comment]
Since both the body and garment models are differentiable parametric models, you can simply optimize the parameter using the chamfer loss. I'll post a demo code maybe this weekend.

**Comment by Vikas-Sony** [comment]
Thanks a lot! I will try to figure out myself till then too.

**Comment by Vikas-Sony** [comment]
Hi, will it be possible to post a demo code anytime soon whenever you are free?

**Comment by Vikas-Sony** [comment]
> 
> 
> Hi, sorry for the late reply. TailorNet uses per-vertex displacement to represent the garment deformation. So your mesh must have the same topology (triangulation) as TailorNet. If you have such meshes (for example you register your garment mesh to TailorNet mesh), a possible solution is to find the closest gamma and use TailorNet then.

May i know how can i do this mesh registration that you were talking about? Sample code or maybe the steps to do it or what exactly does that non-rigid mesh registration do?

**Comment by zycliao** [comment]
Hi. I have little experience in mesh registration and might underestimate the difficulty. Actually, it involves lots of tricks and engineering and I'm not able to dive into it recently. Basically, the underlying algorithm is ICP (iterative closest point). One paper you can refer to is [Clothcap](https://clothcap.is.tue.mpg.de/).

**Comment by Vikas-Sony** [comment]
Hi,
Thanks for the recommendations. :)

**Comment by Vikas-Sony** [comment]
> 
> 
> Since both the body and garment models are differentiable parametric models, you can simply optimize the parameter using the chamfer loss. I'll post a demo code maybe this weekend.

Hi,
I was able to do optimize parameters for body as they were SMPL parameters. But not for garment models. Can you give me pointers on how to do that
